#!/bin/bash
echo ==========start at : `date` ==========
perl /Result/huangfei/RNA_RNAref_version4.1/Enrichement/getKO.pl -glist /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Diff/DEGseq/Control-vs-MT.DEGseq.diffFilter.xls -bg /Disk04/Project/RNA/yilingbo/Database/Database/ref/mm10/NCBI/anno/mm10.ko -outdir /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT && \
perl /Result/huangfei/RNA_RNAref_version4.1/Enrichement/pathfind.pl -fg /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.ko -komap /Database/kegg/RNA/59.3/komap/animal_ko_map.tab -bg /Disk04/Project/RNA/yilingbo/Database/Database/ref/mm10/NCBI/anno/mm10.ko -output /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.path && \
perl /Result/huangfei/RNA_RNAref_version4.1/Enrichement/gpath2geneExpr.pl -p /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.path -d /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Diff/DEGseq/Control-vs-MT.DEGseq.diffFilter.xls -t pathway -o /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/pathway2geneList && \
if [ -e "/Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT/pathway2geneList" ]; then rm -rf /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT/pathway2geneList; fi && \
mv /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/pathway2geneList /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT && \
ln -s /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT/pathway2geneList /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT && \
perl /Result/huangfei/RNA_RNAref_version4.1/Enrichement/pathwayEnrich_UD.pl -d /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Diff/DEGseq/Control-vs-MT.DEGseq.diffFilter.xls -p /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.path -o /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.Pathenrich_top.xls && \
/System/software/R-3.1.0/bin/Rscript /Result/huangfei/RNA_RNAref_version4.1/Enrichement/pathEnrich_UD.R /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.Pathenrich_top.xls /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.Pathenrich_top.pdf && \
/usr/bin/convert -density 300 /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.Pathenrich_top.pdf /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.Pathenrich_top.png && \
/System/software/R-3.1.0/bin/Rscript /Result/huangfei/RNA_RNAref_version4.1/Enrichement/PathwayEnrich.R /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.path Control-vs-MT /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.Pathenrich.pdf && \
/usr/bin/convert -density 300 /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.Pathenrich.pdf /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.Pathenrich.png && \
perl /Result/huangfei/RNA_RNAref_version4.1/Enrichement/keggMap.pl -ko /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.ko -komap /Database/kegg/RNA/59.3/komap/animal_ko_map.tab -diff /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Diff/DEGseq/Control-vs-MT.DEGseq.diffFilter.xls -outdir /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT_map && \
perl /Result/huangfei/RNA_RNAref_version4.1/Enrichement/pathway2class.pl -p /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.path -q 1 -o /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.path_class.xls && \
/System/software/R-3.1.0/bin/Rscript /Result/huangfei/RNA_RNAref_version4.1/Enrichement/draw_pathway2class.R /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.path_class.xls /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.path_class.pdf Control-vs-MT && \
/usr/bin/convert -density 300 /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.path_class.pdf /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.path_class.png && \
/usr/bin/convert -density 300 /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.path_class.pdf /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.path_class.png && \
perl /Result/huangfei/RNA_RNAref_version4.1/Enrichement/pathway_level.pl /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT.path 8 /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT_pathwayLevels && \
 if [ -e "/Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT/Control-vs-MT_pathwayLevels" ]; then rm -rf /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT/Control-vs-MT_pathwayLevels; fi && \
mv /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT_pathwayLevels /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT && \
ln -s /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT/Control-vs-MT_pathwayLevels /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT && \
 if [ -e "/Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT/Control-vs-MT_map" ]; then rm -rf /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT/Control-vs-MT_map; fi && \
mv /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/Control-vs-MT_map /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT && \
ln -s /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT/Control-vs-MT_map /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT && \
cp /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/*.path_class.* /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT && \
perl /Result/huangfei/RNA_RNAref_version4.1/Enrichement/genPathHTML.pl -indir /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT && \
cp /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/*.Pathenrich.* /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT && \
cp /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/*.Pathenrich_top.* /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT && \
cp /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/*.path /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT && \
cp /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/*.htm /Disk04/Project/RNA/ref/A731/project/result/Upload/TGS_Report/Result/Enrichment/Pathway/Control-vs-MT && \
echo ==========end at : `date` ========== && \
echo This-work-is-completed! 1>&2 && \
echo This-work-is-completed! > /Disk04/Project/RNA/ref/A731/project/result/Enrichment//Pathway/Control-vs-MT/pathway_Control-vs-MT.sh.sign
(END)
